### ISSUE TITLE
Add green badge block to plugin

### ISSUE THREAD

**Issue by jamieblomerus** [javiercasares/WPsustainable#14]
I think it would be cool if this website included a block for the green provider badge.

![green-web-badge-hosted-green](https://github.com/javiercasares/WPsustainable/assets/34009701/e0916e4a-943e-4f66-bf7e-08a61fe6ea4d)

If others agree with me that the plugin could benefit from this enhancement I could start crafting a PR for this.

**Comment by davidperezgar** [comment]
Yes, I think a badge is important to show others that the hosting is green.

**Comment by jamieblomerus** [comment]
The biggest question we have to decide upon is whether to implement the green badge from The Green Web Foundation or make a WordPress-themed one.

**Comment by jamieblomerus** [comment]
I have now added a badge block to my existing PR. The badge block uses The Green Web Foundations badge. Feel free to review my PR #13.
