### ISSUE TITLE
Plugin is closed. Why?

### ISSUE THREAD

**Issue by jamieblomerus** [javiercasares/WPsustainable#17]
Today when I went to download the plugin from the Wordpress Plugin Directory on a new website, it did say that the plugin was closed. Why?

@javiercasares Do you know why the plugin is closed and what we can do to fix it?

<img width="1676" alt="Screenshot 2024-03-23 at 10 32 25" src="https://github.com/javiercasares/WPsustainable/assets/34009701/1c48ec47-c0b1-4971-831b-88af2a9b2a55">

**Comment by javiercasares** [comment]
I requested that. The idea was that the Sustainability Team got the project but right now they didn't do it and is not set that they will use it or not for their plugin... so, you can use the latest release: https://github.com/javiercasares/WPsustainable/releases

They have access to this repo and there is the possibility to reopen the plugin if they want, so, we will wait.

In any case, the latest version should work with WordPress 6.5 (AFAIK).
