### ISSUE TITLE
Improve the plugin description so people know to look at the SiteHealth section for the info

### ISSUE THREAD

**Issue by hanopcan** [javiercasares/WPsustainable#5]
When you are looking at the plugin for the first time, there is nothing to indicate where you can find the information. It might be helpful to change the plugin description so people know to look at the Site Health part of the dashboard.

Currently this is what a new user sees:

![Screenshot 2022-12-09 at 12 46 35](https://user-images.githubusercontent.com/11687898/206705941-46c82b72-2170-41c2-a466-b910b2ca1a2e.jpg)

and when it is installed in the plugin list we see this:

![Screenshot 2022-12-09 at 12 46 23](https://user-images.githubusercontent.com/11687898/206706000-8c8b33f3-6d77-4ddc-9182-71ca7e2a39de.jpg)

**Comment by YellowlimeNL** [comment]
If a website is hosted green, that confirmation is a bit hided under the 'passed tests' section. However it would be nice if you get a confirmation once on screen that your website is hosted green.

**Comment by hanopcan** [comment]
> If a website is hosted green, that confirmation is a bit hided under the 'passed tests' section. However it would be nice if you get a confirmation once on screen that your website is hosted green.

Hey @YellowlimeNL I think your suggestion is a great one, but I don't think it belongs inside this issue. What I am talking about is something different. It might better for you to make a new issue describing your idea rather than muddling it in here.

**Comment by hanopcan** [comment]
I'll add a suggestion for the text shortly. I've run out of time today!

**Comment by YellowlimeNL** [comment]
> > If a website is hosted green, that confirmation is a bit hided under the 'passed tests' section. However it would be nice if you get a confirmation once on screen that your website is hosted green.
> 
> Hey @YellowlimeNL I think your suggestion is a great one, but I don't think it belongs inside this issue. What I am talking about is something different. It might better for you to make a new issue describing your idea rather than muddling it in here.

Good suggestion @hanopcan, I will open a seperate 'issue'

**Comment by jamieblomerus** [comment]
This seems to be resolved as the readme.txt:11 reads as follows:

> Check the sustainability from your hosting company and the CO2 generated by your IP address. **Sustainability findings will be available within Tools > Site Health > Status > Passed Tests**.

Therefore this issue shall be closed. @javiercasares
