### ISSUE TITLE
Provide more information around non-green results

### ISSUE THREAD

**Issue by fershad** [javiercasares/WPsustainable#7]
When the [`greencheck` test comes back as `false`](https://github.com/javiercasares/WPsustainable/blob/main/includes/class-health.php#L94-L103) (not a known green web host), it would help to link out to additional information about _why_ this might be the case.

The Green Web Foundation have an FAQ that explains why greencheck results might return `false`. Linking to this could help head off a lot of questions from folks who think their site should be returning a green result.
https://www.thegreenwebfoundation.org/support/why-does-my-website-show-up-as-grey-in-the-green-web-checker/

Proposed wording:
https://github.com/javiercasares/WPsustainable/blob/e8276469764ed2708c521e0d2099a7cfc74e99cf/includes/class-health.php#L101
```php
_( 'is not using green energy for your site. <a href="https://www.thegreenwebfoundation.org/support/why-does-my-website-show-up-as-grey-in-the-green-web-checker/">Why am I seeing this result?</a>', 'wpsustainable' )
```

**Comment by jamieblomerus** [comment]
I have opened pull request #13 for this issue.
